---
- name: install epel repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: install centos-release-scl-rh
  yum:
    name: "centos-release-scl-rh"
    state: oresent

- name: install pip
  yum:
    name: python-pip
    state: present

- name: install dumb-init
  pip:
    name: dumb-init
    version: "{{ manageiq_dumb_init_version }}"

- name: download manageiq repo file
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/manageiq/ManageIQ-Fine/repo/epel-7/manageiq-ManageIQ-Fine-epel-7.repo
    dest: /etc/yum.repos.d/manageiq-ManageIQ-Fine-epel-7.repo

- name: install PostgreSQL repo rpm
  yum:
    name: "{{ manageiq_postgresql_repo_url }}"
    state: present

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "centos-release-scl-rh"
    - "bison"
    - "bzip2"
    - "cmake"
    - "file"
    - "gcc-c++"
    - "git"
    - "libcurl-devel"
    - "libffi-devel"
    - "libtool"
    - "libxml2-devel"
    - "libxslt-devel"
    - "libyaml-devel"
    - "make"
    - "memcached"
    - "net-tools"
    - "nodejs"
    - "openssl-devel"
    - "openscap-scanner"
    - "patch"
    #    - "postgresql{{ manageiq_postgresql_version_short }}-server"
    #    - "postgresql{{ manageiq_postgresql_version_short }}-devel"
    #    - "repmgr{{ manageiq_postgresql_version_short }}"
    - "rh-postgresql95-postgresql-server"
    - "rh-postgresql95-postgresql-devel"
    - "rh-postgresql95-postgresql-pglogical"
    - "rh-postgresql95-repmgr"
    - "readline-devel"
    - "sqlite-devel"
    - "sysvinit-tools"
    - "which"
    - "httpd"
    - "mod_ssl"
    - "mod_auth_kerb"
    - "mod_authnz_pam"
    - "mod_intercept_form_submit"
    - "mod_lookup_identity"
    - "initscripts"
    - "npm"
    - "chrony"
    - "psmisc"
    - "lvm2"
    - "openldap-clients"
    - "gdbm-devel"
    - "cronie"
    - "logrotate"
    - "http-parser"

- name: delete all files unnecessary systemd files
  file:
    path: "{{ item }}/"
    state: absent
  with_items:
    - "/lib/systemd/system/sysinit.target.wants"
    - "/lib/systemd/system/multi-user.target.wants"
    - "/lib/systemd/system/local-fs.target.wants"
    - "/lib/systemd/system/basic.target.wants"
    - "/lib/systemd/system/anaconda.target.wants"

- name: find /etc/systemd/system files to be deleted
  find:
    paths:
      - "/etc/systemd/system"
    patterns: "/*.wants/*"
  register: find_results_etc_systemd

- name: find lib/systemd/system files to be deleted
  find:
    paths:
      - "/lib/systemd/system/sockets.target.wants"
    patterns:
      - "/*udev*"
      - "/*initctl*"
  register: find_results_lib_systemd

- name: delete systemd files using patterns
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items:
    - "{{ find_results_etc_systemd['files'] }}"
    - "{{ find_results_lib_systemd['files'] }}"

- name: download chruby
  get_url:
    url: "{{ manageiq_chruby_url }}"
    dest: "/usr/src/{{ manageiq_chruby_tgz_file }}"

- name: untar chruby file
  unarchive:
    src: "/usr/src/{{ manageiq_chruby_tgz_file }}"
    dest: "/usr/src/"
    remote_src: yes

- name: run chruby make install
  command: make install
  args:
    chdir: "/usr/src/chruby-{{ manageiq_chruby_version }}"

- name: run chruby setup.sh
  command: scripts/setup.sh
  args:
    chdir: "/usr/src/chruby-{{ manageiq_chruby_version }}"

- name: create /root directory
  file:
    path: /root
    state: directory
    owner: root
    group: root
    mode: 0755

- name: ensure file /root/.gemrc exists
  copy:
    content: ""
    dest: /root/.gemrc
    owner: root
    group: root
    mode: 0644

- name: ensure file /root/.bashrc exists
  file:
    path: /root/.bashrc
    state: file
    owner: root
    group: root
    mode: 0644

- name: ensure file /root/.bash_profile exists
  file:
    path: /root/.bash_profile
    state: file
    owner: root
    group: root
    mode: 0644

- name: ensure the line in .gemrc
  lineinfile:
    path: /root/.gemrc
    state: present
    line: "gem: --no-ri --no-rdoc --no-document"

- name: ensure the line in .bashrc
  lineinfile:
    path: /root/.bashrc
    state: present
    line: "source /usr/local/share/chruby/chruby.sh"

- name: download ruby-install
  get_url:
    url: "{{ manageiq_rubyinstall_url }}"
    dest: "/usr/src/{{ manageiq_rubyinstall_tgz_file }}"

- name: untar ruby-install file
  unarchive:
    src: "/usr/src/{{ manageiq_rubyinstall_tgz_file }}"
    dest: "/usr/src/"
    remote_src: yes

- name: run ruby-install make install
  command: make install
  args:
    chdir: "/usr/src/ruby-install-{{ manageiq_rubyinstall_version }}"

- name: run ruby-install
  command: "ruby-install ruby {{ manageiq_ruby_version }} -- --disable-install-doc"

- name: ensure the line in .bash_profile
  lineinfile:
    path: /root/.bash_profile
    state: present
    line: "chruby ruby-{{ manageiq_ruby_version }}"

- name: create necessary manageiq directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ manageiq_app_root }}"
    - "{{ manageiq_appliance_root }}"
    - "{{ manageiq_sui_root }}"

- name: create manageiq symlink
  file:
    src: "{{ manageiq_app_root }}"
    dest: /opt/manageiq/manageiq
    owner: root
    group: root
    state: link

- name: download manageiq release
  get_url:
    url: "https://github.com/ManageIQ/manageiq/tarball/{{ manageiq_release_name }}"
    dest: "/usr/src/manageiq-{{ manageiq_release_name }}"

- name: untar manageiq
  unarchive:
    src: "/usr/src/manageiq-{{ manageiq_release_name }}"
    dest: "{{ manageiq_app_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: download manageiq-appliance release
  get_url:
    url: "https://github.com/ManageIQ/manageiq-appliance/tarball/{{ manageiq_release_name }}"
    dest: "/usr/src/manageiq-appliance-{{ manageiq_release_name }}"

- name: untar manageiq-appliance
  unarchive:
    src: "/usr/src/manageiq-appliance-{{ manageiq_release_name }}"
    dest: "{{ manageiq_appliance_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: download manageiq-ui-service release
  get_url:
    url: "https://github.com/ManageIQ/manageiq-ui-service/tarball/{{ manageiq_release_name }}"
    dest: "/usr/src/manageiq-ui-service-{{ manageiq_release_name }}"

- name: untar manageiq-appliance
  unarchive:
    src: "/usr/src/manageiq-ui-service-{{ manageiq_release_name }}"
    dest: "{{ manageiq_sui_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: run appliance_root setup
  command: ./setup
  args:
    chdir: "{{ manageiq_appliance_root }}"

- name: add necessary lines to /etc/default/evm
  lineinfile:
    path: /etc/default/evm
    state: present
    line: "{{ item }}"
  with_items:
    - "export APP_ROOT={{ manageiq_app_root }}"
    - "export CONTAINER=true"
    - "export PATH=$PATH:/opt/rubies/ruby-{{ manageiq_ruby_version }}/bin"

- name: create app_root/log/apache
  file:
    path: "{{ manageiq_app_root }}/log/apache"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: backup and modify ssl.conf
  copy:
    content: "# This file intentionally left blank. ManageIQ maintains its own SSL configuration"
    dest: /etc/httpd/conf.d/ssl.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
    remote_src: yes
    
- name: copy cable.yml.sample
  copy:
    src: "{{ manageiq_app_root }}/config/cable.yml.sample"
    dest: "{{ manageiq_app_root }}/config/cable.yml"
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: run source /etc/default/evm
  shell: "source /etc/default/evm"
  args:
    chdir: "{{ manageiq_app_root }}"

- name: install npm packages bower, yarn
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items:
    - "bower"
    - "yarn"

- name: install gem pg
  shell: "gem install pg -v '0.18.4' -- --with-pg-include=/usr/pgsql-{{ manageiq_postgresql_version }}/include --with-pg-config=/usr/pgsql-{{ manageiq_postgresql_version }}/bin/pg_config"
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/rubies/ruby-{{ manageiq_ruby_version }}/bin"

- name: gem install bundler
  shell: source /etc/default/evm && gem install bundler --conservative

- name: bower install
  shell: source /etc/default/evm && bower install --allow-root -F --silent --config.analytics=false
  args:
    chdir: "{{ manageiq_app_root }}"

- name: bundle install
  shell: source /etc/default/evm && bundle install
  args:
    chdir: "{{ manageiq_app_root }}"

- name: clear rails log and tmp
  shell: source /etc/default/evm && bin/rails log:clear tmp:clear
  args:
    chdir: "{{ manageiq_app_root }}"

- name: start memcached
  shell: "memcached -u root &"

- name: evm compile_assets
  shell: source /etc/default/evm && rake evm:compile_assets
  args:
    chdir: "{{ manageiq_app_root }}"

- name: evm compile_sti_loader
  shell: source /etc/default/evm && rake evm:compile_sti_loader
  args:
    chdir: "{{ manageiq_app_root }}"

- name: stop memcached
  shell: pkill memcached

- name: install build SUI
  shell: "source /etc/default/evm && cd {{ manageiq_sui_root }} && yarn install && yarn run build"
  args:
    chdir: "{{ manageiq_sui_root }}"


- name: copy systemd appliance-initialize service file
  template:
    src: appliance-initialize.service.j2
    dest: /usr/lib/systemd/system/appliance-initialize.service
    owner: root
    group: root
    mode: 0644

- name: copy appliance-initialize shell script
  template:
    src: appliance-initialize.sh.j2
    dest: /bin/appliance-initialize.sh
    owner: root
    group: root
    mode: 0755

- name: create docker_initdb
  template:
    src: docker_initdb.j2
    dest: "/usr/bin/docker_initdb"
    owner: root
    group: root
    mode: 0755

- name: replace /etc/default/evm_postgres
  template:
    src: evm_postgres.j2
    dest: /etc/default/evm_postgres
    owner: root
    group: root
    mode: 0644

- name: create /var/run/postgresql
  file:
    path: /var/run/postgresql
    state: directory
    owner: postgres
    group: postgres
    mode: 0755

    #- name: enable systemd services
    #  systemd:
    #    name: "{{ item }}"
    #    enabled: yes
    #  with_items:
    #    - "memcached"
    #    - "appliance-initialize"
    #    - "evmserverd"
    #    - "evminit"
    #    - "evm-watchdog"
    #    - "miqvmstat"
    #    - "miqtop"
    #    - "crond"
