---
- name: enable epel repository
  yum:
    name: epel-release
    state: present

- name: install pip
  yum:
    name: python-pip
    state: present

- name: install dumb-init
  pip:
    name: dumb-init
    version: "{{ manageiq_dumb_init_version }}"
