---
- name: enable epel repository
  yum:
    name: epel-release
    state: present

- name: install pip
  yum:
    name: python-pip
    state: present

- name: install dumb-init
  pip:
    name: dumb-init
    version: "{{ manageiq_dumb_init_version }}"

- name: download manageiq repo file
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/manageiq/ManageIQ-Fine/repo/epel-7/manageiq-ManageIQ-Fine-epel-7.repo
    dest: /etc/yum.repos.d/manageiq-ManageIQ-Fine-epel-7.repo

- name: install PostgreSQL repo rpm
  yum:
    name: "{{ manageiq_postgresql_repo_url }}"
    state: present

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "centos-release-scl-rh"
    - "bison"
    - "bzip2"
    - "cmake"
    - "file"
    - "gcc-c++"
    - "git"
    - "libcurl-devel"
    - "libffi-devel"
    - "libtool"
    - "libxml2-devel"
    - "libxslt-devel"
    - "libyaml-devel"
    - "make"
    - "memcached"
    - "net-tools"
    - "nodejs"
    - "openssl-devel"
    - "openscap-scanner"
    - "patch"
    - "postgresql{{ manageiq_postgresql_version }}-server"
    - "postgresql{{ manageiq_postgresql_version }}-devel"
    - "repmgr{{ manageiq_postgresql_version }}"
    - "readline-devel"
    - "sqlite-devel"
    - "sysvinit-tools"
    - "which"
    - "httpd"
    - "mod_ssl"
    - "mod_auth_kerb"
    - "mod_authnz_pam"
    - "mod_intercept_form_submit"
    - "mod_lookup_identity"
    - "initscripts"
    - "npm"
    - "chrony"
    - "psmisc"
    - "lvm2"
    - "openldap-clients"
    - "gdbm-devel"
    - "cronie"
    - "logrotate"
    - "http-parser"

- name: delete all files unnecessary systemd files
  file:
    path: "{{ item }}/"
    state: absent
  with_items:
    - "/lib/systemd/system/sysinit.target.wants"
    - "/lib/systemd/system/multi-user.target.wants"
    - "/lib/systemd/system/local-fs.target.wants"
    - "/lib/systemd/system/basic.target.wants"
    - "/lib/systemd/system/anaconda.target.wants"

- name: find /etc/systemd/system files to be deleted
  find:
    paths:
      - "/etc/systemd/system"
    patterns: "/*.wants/*"
  register: find_results_etc_systemd

- name: find lib/systemd/system files to be deleted
  find:
    paths:
      - "/lib/systemd/system/sockets.target.wants"
    patterns:
      - "/*udev*"
      - "/*initctl*"
  register: find_results_lib_systemd

- name: delete systemd files using patterns
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items:
    - "{{ find_results_etc_systemd['files'] }}"
    - "{{ find_results_lib_systemd['files'] }}"

